export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  region: 'Americas' | 'Europe' | 'Asia' | 'MiddleEastAfrica' | 'Universal';
  dir?: 'ltr' | 'rtl';
  speechLang: string;
}

export const ALL_LANGUAGES: Language[] = [
  // 1. Américas & Ibero-Romance
  {
    code: 'pt',
    name: 'Portuguese (Brazil)',
    nativeName: 'Português (Brasil)',
    flag: '🇧🇷',
    region: 'Americas',
    dir: 'ltr',
    speechLang: 'pt-BR',
  },
  {
    code: 'pt-PT',
    name: 'Portuguese (Portugal)',
    nativeName: 'Português (Portugal)',
    flag: '🇵🇹',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'pt-PT',
  },
  {
    code: 'en',
    name: 'English (US/Global)',
    nativeName: 'English',
    flag: '🇺🇸',
    region: 'Americas',
    dir: 'ltr',
    speechLang: 'en-US',
  },
  {
    code: 'en-GB',
    name: 'English (UK)',
    nativeName: 'English (UK)',
    flag: '🇬🇧',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'en-GB',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'es-ES',
  },
  {
    code: 'es-MX',
    name: 'Spanish (Latin America)',
    nativeName: 'Español (Latinoamérica)',
    flag: '🇲🇽',
    region: 'Americas',
    dir: 'ltr',
    speechLang: 'es-MX',
  },

  // 2. Europa
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'fr-FR',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'de-DE',
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'it-IT',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'ru-RU',
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    flag: '🇺🇦',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'uk-UA',
  },
  {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    flag: '🇵🇱',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'pl-PL',
  },
  {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    flag: '🇳🇱',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'nl-NL',
  },
  {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    flag: '🇸🇪',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'sv-SE',
  },
  {
    code: 'no',
    name: 'Norwegian',
    nativeName: 'Norsk',
    flag: '🇳🇴',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'nb-NO',
  },
  {
    code: 'da',
    name: 'Danish',
    nativeName: 'Dansk',
    flag: '🇩🇰',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'da-DK',
  },
  {
    code: 'fi',
    name: 'Finnish',
    nativeName: 'Suomi',
    flag: '🇫🇮',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'fi-FI',
  },
  {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    flag: '🇬🇷',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'el-GR',
  },
  {
    code: 'cs',
    name: 'Czech',
    nativeName: 'Čeština',
    flag: '🇨🇿',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'cs-CZ',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    nativeName: 'Magyar',
    flag: '🇭🇺',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'hu-HU',
  },
  {
    code: 'ro',
    name: 'Romanian',
    nativeName: 'Română',
    flag: '🇷🇴',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'ro-RO',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    nativeName: 'Български',
    flag: '🇧🇬',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'bg-BG',
  },
  {
    code: 'hr',
    name: 'Croatian',
    nativeName: 'Hrvatski',
    flag: '🇭🇷',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'hr-HR',
  },
  {
    code: 'sk',
    name: 'Slovak',
    nativeName: 'Slovenčina',
    flag: '🇸🇰',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'sk-SK',
  },
  {
    code: 'sr',
    name: 'Serbian',
    nativeName: 'Српски',
    flag: '🇷🇸',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'sr-RS',
  },
  {
    code: 'ca',
    name: 'Catalan',
    nativeName: 'Català',
    flag: '🇦🇩',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'ca-ES',
  },
  {
    code: 'ga',
    name: 'Irish',
    nativeName: 'Gaeilge',
    flag: '🇮🇪',
    region: 'Europe',
    dir: 'ltr',
    speechLang: 'ga-IE',
  },

  // 3. Ásia & Pacífico
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'ja-JP',
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    nativeName: '简体中文',
    flag: '🇨🇳',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'zh-CN',
  },
  {
    code: 'zh-TW',
    name: 'Chinese (Traditional)',
    nativeName: '繁體中文',
    flag: '🇹🇼',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'zh-TW',
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'ko-KR',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'hi-IN',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇧🇩',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'bn-BD',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'vi-VN',
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    flag: '🇮🇩',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'id-ID',
  },
  {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    flag: '🇲🇾',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'ms-MY',
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    flag: '🇹🇭',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'th-TH',
  },
  {
    code: 'tl',
    name: 'Tagalog (Filipino)',
    nativeName: 'Wikang Tagalog',
    flag: '🇵🇭',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'fil-PH',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    region: 'Asia',
    dir: 'ltr',
    speechLang: 'ta-IN',
  },

  // 4. Oriente Médio & África
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    region: 'MiddleEastAfrica',
    dir: 'rtl',
    speechLang: 'ar-SA',
  },
  {
    code: 'he',
    name: 'Hebrew',
    nativeName: 'עברית',
    flag: '🇮🇱',
    region: 'MiddleEastAfrica',
    dir: 'rtl',
    speechLang: 'he-IL',
  },
  {
    code: 'fa',
    name: 'Persian (Farsi)',
    nativeName: 'فارسی',
    flag: '🇮🇷',
    region: 'MiddleEastAfrica',
    dir: 'rtl',
    speechLang: 'fa-IR',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    region: 'MiddleEastAfrica',
    dir: 'ltr',
    speechLang: 'tr-TR',
  },
  {
    code: 'sw',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    flag: '🇰🇪',
    region: 'MiddleEastAfrica',
    dir: 'ltr',
    speechLang: 'sw-KE',
  },
  {
    code: 'af',
    name: 'Afrikaans',
    nativeName: 'Afrikaans',
    flag: '🇿🇦',
    region: 'MiddleEastAfrica',
    dir: 'ltr',
    speechLang: 'af-ZA',
  },

  // 5. Línguas Universais & Históricas
  {
    code: 'eo',
    name: 'Esperanto',
    nativeName: 'Esperanto',
    flag: '🟢',
    region: 'Universal',
    dir: 'ltr',
    speechLang: 'eo',
  },
  {
    code: 'la',
    name: 'Latin',
    nativeName: 'Latina',
    flag: '🏛️',
    region: 'Universal',
    dir: 'ltr',
    speechLang: 'la',
  },
  {
    code: 'ia',
    name: 'Interlingua',
    nativeName: 'Interlingua',
    flag: '🌐',
    region: 'Universal',
    dir: 'ltr',
    speechLang: 'ia',
  },
];

export const DEFAULT_LANGUAGE: Language = ALL_LANGUAGES[0]; // pt

export const getLanguageByCode = (code: string): Language => {
  const found = ALL_LANGUAGES.find(
    (l) => l.code.toLowerCase() === code.toLowerCase() || l.code.split('-')[0] === code.toLowerCase()
  );
  return found || DEFAULT_LANGUAGE;
};
